### ISSUE TITLE
Problem with connecting to ssh backend

### ISSUE THREAD

**Issue by Giraphe** [aenima-x/BlackHole#8]
Hi,

I'm setting up the ssh bastion as explained.
The server is running, I connect to the web interface and configured the accounts and the backend ssh servers.
I created a sample user and log in with ssh to the bastion. I get the menus showing the available connections upon ssh connection.

This is where I am stuck. When I choose a server to connect and hit enter I just have a message saying "Log path not found".

I tried multiple log location In the file settings.py : 
/var/log
/opt/Blackhole/blackhole
~/
But it never stop complaining on login.
The file doesn't get created either on the bastion host.

I do have launched a redis server and in the web interface I don't see any active sessions ( my user being in the ssh menu)

Thanks

Raphaël

**Comment by aenima-x** [comment]
Hello, try set log_path to /tmp and try again

**Comment by Giraphe** [comment]
Hi,

You're right it works now : I can connect to ssh backend server and the log files are created on the bastion host.

Thanks for helping

Raphaël
